--------------------------------------------------------
--  File created - Friday-October-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MP_USER
--------------------------------------------------------

  CREATE TABLE "RECOM"."MP_USER" 
   (	"USER_NAME" VARCHAR2(50 BYTE), 
	"P_DATA" VARCHAR2(150 BYTE), 
	"MAKER_ID" VARCHAR2(50 BYTE) DEFAULT USER, 
	"MAKER_TIME" DATE DEFAULT SYSDATE, 
	"CHECKER_ID" VARCHAR2(50 BYTE), 
	"CHECKER_TIME" DATE, 
	"STATUS" NUMBER DEFAULT 0, 
	"ROLES" VARCHAR2(100 CHAR), 
	"SECRET_KEY" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into RECOM.MP_USER
SET DEFINE OFF;
Insert into RECOM.MP_USER (USER_NAME,P_DATA,MAKER_ID,MAKER_TIME,CHECKER_ID,CHECKER_TIME,STATUS,ROLES,SECRET_KEY) values ('admin','$2a$10$ei4Na0xTtj9cru5fLJSvy.PyFG5awXWmFFLtzw0HUR1jn0i2Nm1qG','admin',to_date('21-OCT-21','DD-MON-RR'),null,null,1,'ADMIN','user-secret-key');
--------------------------------------------------------
--  DDL for Index MP_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECOM"."MP_USER_PK" ON "RECOM"."MP_USER" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MP_USER
--------------------------------------------------------

  ALTER TABLE "RECOM"."MP_USER" ADD CONSTRAINT "MP_USER_PK" PRIMARY KEY ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RECOM"."MP_USER" MODIFY ("ROLES" NOT NULL ENABLE);
  ALTER TABLE "RECOM"."MP_USER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RECOM"."MP_USER" MODIFY ("MAKER_TIME" NOT NULL ENABLE);
  ALTER TABLE "RECOM"."MP_USER" MODIFY ("MAKER_ID" NOT NULL ENABLE);
  ALTER TABLE "RECOM"."MP_USER" MODIFY ("P_DATA" NOT NULL ENABLE);
  ALTER TABLE "RECOM"."MP_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);





--TEST PEOCEDURE CALLED FROM APPLICATION
create or replace PROCEDURE TEST_PROCEDURE(USER_NAME IN OUT VARCHAR2, 
SECRET_KEY OUT  VARCHAR2)
AS BEGIN
    SECRET_KEY := 'mykey';
END;